title: Eitan Podolich
#logo: /assets/img/headshot_circle.png
description: Explore my skills and featured projects to see how I showcase my expertise in DevOps and automation.
show_downloads: false
remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme
github:
  another_url: https://github.com/EITANPOD/devops-killer-project.git
